##Examen Data Vizualisation sur le Dataset Chronic Kidney Disease

In [1]:
# importation du dataset
!pip install ucimlrepo

# Imports
import pandas as pd
from ucimlrepo import fetch_ucirepo

# Chargement du dataset
chronic_kidney_disease = fetch_ucirepo(id=336)

# Séparation features et target
X = chronic_kidney_disease.data.features
y = chronic_kidney_disease.data.targets

# Fusion en un seul DataFrame
df = pd.concat([X, y], axis=1)

# Premier aperçu
print(df.shape)
df.head()

Requirement already satisfied: ucimlrepo in /usr/local/lib/python3.12/dist-packages (0.0.7)
Requirement already satisfied: pandas>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ucimlrepo) (2.2.2)
Requirement already satisfied: certifi>=2020.12.5 in /usr/local/lib/python3.12/dist-packages (from ucimlrepo) (2026.4.22)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.17.0)
(400, 25)

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wbcc,rbcc,htn,dm,cad,appet,pe,ane,class
0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,121.0,...,44.0,7800.0,5.2,yes,yes,no,good,no,no,ckd
1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,NaN,...,38.0,6000.0,NaN,no,no,no,good,no,no,ckd
2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,423.0,...,31.0,7500.0,NaN,no,yes,no,poor,no,yes,ckd
3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,117.0,...,32.0,6700.0,3.9,yes,no,no,poor,yes,yes,ckd
4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,106.0,...,35.0,7300.0,4.6,no,no,no,good,no,no,ckd

##Inspection des donnees

In [2]:
df.info()
# on a 400 observations sur 25 variables

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 25 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     391 non-null    float64
 1   bp      388 non-null    float64
 2   sg      353 non-null    float64
 3   al      354 non-null    float64
 4   su      351 non-null    float64
 5   rbc     248 non-null    object
 6   pc      335 non-null    object
 7   pcc     396 non-null    object
 8   ba      396 non-null    object
 9   bgr     356 non-null    float64
 10  bu      381 non-null    float64
 11  sc      383 non-null    float64
 12  sod     313 non-null    float64
 13  pot     312 non-null    float64
 14  hemo    348 non-null    float64
 15  pcv     329 non-null    float64
 16  wbcc    294 non-null    float64
 17  rbcc    269 non-null    float64
 18  htn     398 non-null    object
 19  dm      398 non-null    object
 20  cad     398 non-null    object
 21  appet   399 non-null    object
 22  pe      399 non-null    object
 23  ane     399 non-null    object
 24  class   400 non-null    object
dtypes: float64(14), object(11)
memory usage: 78.3+ KB

In [3]:
# Modification de certains type fro some variables en se referant a la documentation du dataset
cols_entiers = ['age','bu','bp','bgr','sod','pcv','wbcc']
df[cols_entiers] = df[cols_entiers].round(0).astype('Int64')
df.dtypes

age        Int64
bp         Int64
sg       float64
al       float64
su       float64
rbc       object
pc        object
pcc       object
ba        object
bgr        Int64
bu         Int64
sc       float64
sod        Int64
pot      float64
hemo     float64
pcv        Int64
wbcc       Int64
rbcc     float64
htn       object
dm        object
cad       object
appet     object
pe        object
ane       object
class     object
dtype: object

In [4]:
df.isnull().sum()
# on constate que presque toutes les variables ont des valeurs manquantes.

age        9
bp        12
sg        47
al        46
su        49
rbc      152
pc        65
pcc        4
ba         4
bgr       44
bu        19
sc        17
sod       87
pot       88
hemo      52
pcv       71
wbcc     106
rbcc     131
htn        2
dm         2
cad        2
appet      1
pe         1
ane        1
class      0
dtype: int64

In [5]:
df.duplicated().sum()
# On a aucune valeur dupliquée.

np.int64(0)

In [6]:
df.describe(include='all')

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wbcc,rbcc,htn,dm,cad,appet,pe,ane,class
count,391.0,388.0,353.000000,354.000000,351.000000,248,335,396,396,356.0,...,329.0,294.0,269.000000,398,398,398,399,399,399,400
unique,<NA>,<NA>,NaN,NaN,NaN,2,2,2,2,<NA>,...,<NA>,<NA>,NaN,2,3,2,2,2,2,3
top,<NA>,<NA>,NaN,NaN,NaN,normal,normal,notpresent,notpresent,<NA>,...,<NA>,<NA>,NaN,no,no,no,good,no,no,ckd
freq,<NA>,<NA>,NaN,NaN,NaN,201,259,354,374,<NA>,...,<NA>,<NA>,NaN,251,260,364,317,323,339,248
mean,51.483376,76.469072,1.017408,1.016949,0.450142,NaN,NaN,NaN,NaN,148.036517,...,38.884498,8406.122449,4.707435,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,17.169714,13.683637,0.005717,1.352679,1.099191,NaN,NaN,NaN,NaN,79.281714,...,8.990105,2944.47419,1.025323,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,2.0,50.0,1.005000,0.000000,0.000000,NaN,NaN,NaN,NaN,22.0,...,9.0,2200.0,2.100000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,42.0,70.0,1.010000,0.000000,0.000000,NaN,NaN,NaN,NaN,99.0,...,32.0,6500.0,3.900000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,55.0,80.0,1.020000,0.000000,0.000000,NaN,NaN,NaN,NaN,121.0,...,40.0,8000.0,4.800000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,64.5,80.0,1.020000,2.000000,0.000000,NaN,NaN,NaN,NaN,163.0,...,45.0,9800.0,5.400000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,90.0,180.0,1.025000,5.000000,5.000000,NaN,NaN,NaN,NaN,490.0,...,54.0,26400.0,8.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN

##Analyse Univariee

In [7]:
# Choix des variables numeriques importantes

import plotly.express as px
# Encodage de la variable target ckd=1 notckd=0
df['target']=df['class'].map({'ckd':1 , 'notckd':0})
df['target']=df['target'].astype('Int64')
df['target'].unique()

# correlation avec les autres variables
df.corr(numeric_only=True)['target'].sort_values(ascending=False)
# On prendra les valeurs dont |cor|>0.5
var_num=['al','bgr','sod','hemo','rbcc','pcv','sg']
# mais on va conserver le sodium et le blood glucose random pour eviter de perdre des informations
# choix par visualisation
# Heatmap

corr = df[var_num + ['target']].corr()

fig = px.imshow(
    corr,
    text_auto=True,
    aspect='auto',
    title='Matrice de corrélation',
    template='plotly_white'
)

fig.show()

In [8]:
# Visualisation avec Plotly
var_num=['al','bgr','sod','hemo','rbcc','pcv','sg']
for var in var_num:

    # Histogramme
    fig = px.histogram(df.dropna(subset=[var]), x=var, title=f"Distribution de {var}")
    fig.show()

    # Boxplot
    fig = px.box(df.dropna(subset=[var]), x=var, title=f"Boxplot de {var}")
    fig.show()

    # Statistiques
    print(f"Statistiques de {var} :")
    print(df[var].describe())
    print("\n----------------------\n")

Statistiques de al :
count    354.000000
mean       1.016949
std        1.352679
min        0.000000
25%        0.000000
50%        0.000000
75%        2.000000
max        5.000000
Name: al, dtype: float64

----------------------

Statistiques de bgr :
count         356.0
mean     148.036517
std       79.281714
min            22.0
25%            99.0
50%           121.0
75%           163.0
max           490.0
Name: bgr, dtype: Float64

----------------------

Statistiques de sod :
count         313.0
mean     137.527157
std       10.429252
min             4.0
25%           135.0
50%           138.0
75%           142.0
max           163.0
Name: sod, dtype: Float64

----------------------

Statistiques de hemo :
count    348.000000
mean      12.526437
std        2.912587
min        3.100000
25%       10.300000
50%       12.650000
75%       15.000000
max       17.800000
Name: hemo, dtype: float64

----------------------

Statistiques de rbcc :
count    269.000000
mean       4.707435
std        1.025323
min        2.100000
25%        3.900000
50%        4.800000
75%        5.400000
max        8.000000
Name: rbcc, dtype: float64

----------------------

Statistiques de pcv :
count        329.0
mean     38.884498
std       8.990105
min            9.0
25%           32.0
50%           40.0
75%           45.0
max           54.0
Name: pcv, dtype: Float64

----------------------

Statistiques de sg :
count    353.000000
mean       1.017408
std        0.005717
min        1.005000
25%        1.010000
50%        1.020000
75%        1.020000
max        1.025000
Name: sg, dtype: float64

----------------------

In [9]:
# chois des variables categorielles avec le p-value
! pip install spicy
from scipy.stats import chi2_contingency

var_cat = ['rbc', 'pc', 'pcc', 'ba', 'htn', 'dm', 'cad', 'appet', 'pe', 'ane']

for var in var_cat:
    contingency_table = pd.crosstab(df[var], df['class'])
    chi2, p, dof, expected = chi2_contingency(contingency_table)
    print(f"{var} → p-value : {p:.4f} {'importante' if p < 0.05 else 'pas importante'}")

# En fait on note que toutes les variables catégorielles ont une p-value supérieure à 0,05 donc elles sont toutes importantes.
# donc on se base sur le critère médical pour extraire les plus importantes.

Requirement already satisfied: spicy in /usr/local/lib/python3.12/dist-packages (0.16.0)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from spicy) (1.16.3)
Requirement already satisfied: numpy<2.6,>=1.25.2 in /usr/local/lib/python3.12/dist-packages (from scipy->spicy) (2.0.2)
rbc → p-value : 0.0000 importante
pc → p-value : 0.0000 importante
pcc → p-value : 0.0000 importante
ba → p-value : 0.0010 importante
htn → p-value : 0.0000 importante
dm → p-value : 0.0000 importante
cad → p-value : 0.0000 importante
appet → p-value : 0.0000 importante
pe → p-value : 0.0000 importante
ane → p-value : 0.0000 importante

In [10]:
vars_cat=['dm','appet','ane','rbc','htn']
for var in vars_cat:
    fig = px.bar(df[var].value_counts().reset_index(),
                 x=var, y='count',
                 title=f"Distribution de {var}",
                 color=var)
    fig.show()

In [13]:
# gestion des valeurs manquantes de la variables cible target
df = df.dropna(subset=['target'])
df['target'] = df['target'].astype(int)
df['target'].unique()

array([1, 0])

In [14]:
# Numériques vs target → boxplot groupé
for var in var_num:
    temp = df.dropna(subset=[var]).copy()
    temp[var] = temp[var].astype(float)
    fig = px.box(temp, x='target', y=var,
                 color='target',
                 title=f"{var} selon la classe (ckd vs notckd)")
    fig.show()

In [15]:
# Scatter plot
fig = px.scatter(
    df,
    x='hemo',
    y='pcv',
    color='class',
    title='Relation entre hemoglobin et packed cell volume',
    hover_data=['age']
)

fig.show()

In [16]:
# Catégorielles vs target → bar chart groupé
var_cat_importantes = ['htn', 'dm', 'rbc', 'appet', 'ane']

for var in var_cat_importantes:
    fig = px.histogram(df.dropna(subset=[var]),
                       x=var,
                       color='class',
                       barmode='group',
                       title=f"{var} selon la classe (ckd vs notckd)")
    fig.show()

In [17]:
# Graphique metier
fig = px.histogram(
    df,
    x='htn',
    color='class',
    facet_col='dm',
    barmode='group',
    title='Effet combiné du diabète et de l’hypertension sur la CKD',
    template='plotly_white'
)

fig.show()

##Modelisation

In [18]:
# Verification finale des donnees
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
Index: 398 entries, 0 to 399
Data columns (total 26 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     389 non-null    Int64
 1   bp      386 non-null    Int64
 2   sg      352 non-null    float64
 3   al      353 non-null    float64
 4   su      350 non-null    float64
 5   rbc     247 non-null    object
 6   pc      334 non-null    object
 7   pcc     394 non-null    object
 8   ba      394 non-null    object
 9   bgr     354 non-null    Int64
 10  bu      379 non-null    Int64
 11  sc      381 non-null    float64
 12  sod     311 non-null    Int64
 13  pot     310 non-null    float64
 14  hemo    347 non-null    float64
 15  pcv     328 non-null    Int64
 16  wbcc    292 non-null    Int64
 17  rbcc    268 non-null    float64
 18  htn     396 non-null    object
 19  dm      398 non-null    object
 20  cad     396 non-null    object
 21  appet   397 non-null    object
 22  pe      397 non-null    object
 23  ane     397 non-null    object
 24  class   398 non-null    object
 25  target  398 non-null    int64
dtypes: Int64(7), float64(7), int64(1), object(11)
memory usage: 86.7+ KB

age         9
bp         12
sg         46
al         45
su         48
rbc       151
pc         64
pcc         4
ba          4
bgr        44
bu         19
sc         17
sod        87
pot        88
hemo       51
pcv        70
wbcc      106
rbcc      130
htn         2
dm          0
cad         2
appet       1
pe          1
ane         1
class       0
target      0
dtype: int64

In [25]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Encodage
df['target'] = df['class'].map({'ckd': 1, 'notckd': 0})
df['rbc'] = df['rbc'].astype(str).str.strip().map({'normal': 1, 'abnormal': 0})
df['appet'] = df['appet'].astype(str).str.strip().map({'good': 1, 'poor': 0})
binary_cols = ['htn', 'dm', 'ane']
df[binary_cols] = df[binary_cols].apply(
    lambda x: x.astype(str).str.strip().str.lower().map({'yes': 1, 'no': 0})
)

df = df.dropna(subset=['target'])
df['target'] = df['target'].astype(int)

# Features

# la presence de hemo et pcv font que ce modele a un accuracy de 100% ce qui est cliniquement justifiable et meme ici de par la correlation on peut aussi le justifier
#  cependant on va faire sans ceux ci pour etre plus optionnel
var_num_modif = ['al', 'bgr', 'sod', 'rbcc', 'sg']
features = var_num_modif + ['htn', 'dm', 'ane', 'appet', 'rbc']
X = df[features].copy()

# Convertir tout en float pour éviter les problèmes d'Int64
X = X.astype(float)
y = df['target']

# Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Pipeline
pipe = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler()),
    ('model', LogisticRegression(max_iter=1000))
])

pipe.fit(X_train, y_train)
y_pred = pipe.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

scores = cross_val_score(pipe, X, y, cv=5)
print("\nCross Validation Scores:", scores)
print("Mean CV Accuracy:", scores.mean())
# ce model a un accuracy de 96.25%

/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning:

Skipping features without any observed values: ['htn' 'dm' 'ane' 'appet' 'rbc']. At least one non-missing value is needed for imputation with strategy='median'.

/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning:

Skipping features without any observed values: ['htn' 'dm' 'ane' 'appet' 'rbc']. At least one non-missing value is needed for imputation with strategy='median'.

/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning:

Skipping features without any observed values: ['htn' 'dm' 'ane' 'appet' 'rbc']. At least one non-missing value is needed for imputation with strategy='median'.

/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning:

Skipping features without any observed values: ['htn' 'dm' 'ane' 'appet' 'rbc']. At least one non-missing value is needed for imputation with strategy='median'.

/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning:

Skipping features without any observed values: ['htn' 'dm' 'ane' 'appet' 'rbc']. At least one non-missing value is needed for imputation with strategy='median'.

/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning:

Skipping features without any observed values: ['htn' 'dm' 'ane' 'appet' 'rbc']. At least one non-missing value is needed for imputation with strategy='median'.

/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning:

Skipping features without any observed values: ['htn' 'dm' 'ane' 'appet' 'rbc']. At least one non-missing value is needed for imputation with strategy='median'.

/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning:

Skipping features without any observed values: ['htn' 'dm' 'ane' 'appet' 'rbc']. At least one non-missing value is needed for imputation with strategy='median'.

/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning:

Skipping features without any observed values: ['htn' 'dm' 'ane' 'appet' 'rbc']. At least one non-missing value is needed for imputation with strategy='median'.

Accuracy: 0.9625

Confusion Matrix:
[[28  2]
 [ 1 49]]

Classification Report:
              precision    recall  f1-score   support

           0       0.97      0.93      0.95        30
           1       0.96      0.98      0.97        50

    accuracy                           0.96        80
   macro avg       0.96      0.96      0.96        80
weighted avg       0.96      0.96      0.96        80


Cross Validation Scores: [0.9375     0.9625     0.975      0.96202532 0.93670886]
Mean CV Accuracy: 0.9547468354430378

/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning:

Skipping features without any observed values: ['htn' 'dm' 'ane' 'appet' 'rbc']. At least one non-missing value is needed for imputation with strategy='median'.

/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning:

Skipping features without any observed values: ['htn' 'dm' 'ane' 'appet' 'rbc']. At least one non-missing value is needed for imputation with strategy='median'.

/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning:

Skipping features without any observed values: ['htn' 'dm' 'ane' 'appet' 'rbc']. At least one non-missing value is needed for imputation with strategy='median'.